pyAgreeZone/pyAgreeZone/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

from pyAgreeZone import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('apps.api.urls')),
    url(r'', include('apps.web.urls')),

    # django media 文件访问
    url(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),
]

pyAgreeZone/apps/api/models.py
from django.db import models


class Department(models.Model):
    STATUS_VALID = 1
    STATUS_DELETE = 9
    name = models.CharField(verbose_name='部门名', max_length=11)
    status_choices = (
        (STATUS_VALID, '正常'),
        (STATUS_DELETE, '删除')
    )
    status = models.PositiveSmallIntegerField(verbose_name='状态', choices=status_choices, default=STATUS_VALID)

    def __str__(self):
        return self.name


class UserInfo(models.Model):
    telephone = models.CharField(verbose_name='手机号', max_length=11)
    nickname = models.CharField(verbose_name='昵称', max_length=64)
    avatar = models.CharField(verbose_name='头像', max_length=64, null=True)
    token = models.CharField(verbose_name='用户Token', max_length=64)
    fans_count = models.PositiveIntegerField(verbose_name='粉丝个数', default=0)
    follow = models.ManyToManyField(verbose_name='关注', to='self', blank=True)
    session_key = models.CharField(verbose_name='微信会话秘钥', max_length=32)
    openid = models.CharField(verbose_name='微信用户唯一标识', max_length=32)
    depart = models.OneToOneField(verbose_name='部门', to='Department', null=True, blank=True, on_delete=models.CASCADE)
    DEPART_STATUS_VALID = 1
    DEPART_STATUS_VERIFING = 2
    DEPART_STATUS_INVALID = 3
    depart_status_choices = (
        (DEPART_STATUS_VALID, '已认证'),
        (DEPART_STATUS_VERIFING, '认证中'),
        (DEPART_STATUS_INVALID, '驳回')
    )

    depart_status = models.PositiveIntegerField(verbose_name='部门认证状态', choices=depart_status_choices,
                                                default=DEPART_STATUS_VALID)  # 默认 已认证

    STATUS_VALID = 1
    STATUS_DELETE = 9
    status_choices = (
        (STATUS_VALID, '正常'),
        (STATUS_DELETE, '删除')
    )
    status = models.PositiveSmallIntegerField(verbose_name='用户状态', choices=status_choices, default=STATUS_VALID)

    def __str__(self):
        return self.nickname


class WebUserInfo(models.Model):
    """web管理端用户"""
    nickname = models.CharField(verbose_name='昵称', max_length=64)
    name = models.CharField(verbose_name='账号', max_length=32, unique=True)
    password = models.CharField(verbose_name='密码', max_length=64)

    STATUS_VALID = 1
    STATUS_INVALID = 2
    status_choices = (
        (STATUS_VALID, '正常'),
        (STATUS_INVALID, '不正常')
    )
    status = models.PositiveSmallIntegerField(verbose_name='用户状态', choices=status_choices, default=STATUS_VALID)

    def __str__(self):
        return self.nickname


class Topic(models.Model):
    STATUS_VALID = 1
    STATUS_INVALID = 2
    STATUS_DELETE = 9
    """
    话题
    """
    title = models.CharField(verbose_name='话题', max_length=32)
    count = models.PositiveIntegerField(verbose_name='关注度', default=0)
    status_choices = (
        (STATUS_VALID, '正常'),
        (STATUS_INVALID, '失效')
    )
    status = models.PositiveSmallIntegerField(verbose_name='话题状态', choices=status_choices, default=STATUS_VALID)


class AgreePoint(models.Model):
    """
    赞点
    """
    cover = models.CharField(verbose_name='封面', max_length=128)
    content = models.CharField(verbose_name='内容', max_length=255)
    topic = models.ForeignKey(verbose_name='话题', to='Topic', null=True, blank=True, on_delete=models.CASCADE)
    address = models.CharField(verbose_name='位置', max_length=128, null=True, blank=True)

    user = models.ForeignKey(verbose_name='发布者', to='UserInfo', related_name='agreePoint', on_delete=models.CASCADE)

    favor_count = models.PositiveIntegerField(verbose_name='赞数', default=0)
    viewer_count = models.PositiveIntegerField(verbose_name='浏览数', default=0)
    comment_count = models.PositiveIntegerField(verbose_name='评论数', default=0)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)


class ViewerRecord(models.Model):
    """
    浏览器记录
    """
    agreePoint = models.ForeignKey(verbose_name='赞点', to='AgreePoint', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='用户', to='UserInfo', on_delete=models.CASCADE)


class AgreePointFavorRecord(models.Model):
    """
    赞点记录表
    """
    agreePoint = models.ForeignKey(verbose_name='赞点', to='AgreePoint', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='点赞用户', to='UserInfo', on_delete=models.CASCADE)


class CommentRecord(models.Model):
    """
    评论记录表
    """
    agreePoint = models.ForeignKey(verbose_name='赞点', to='AgreePoint', on_delete=models.CASCADE)
    content = models.CharField(verbose_name='评论内容', max_length=255)
    user = models.ForeignKey(verbose_name='评论者', to='UserInfo', on_delete=models.CASCADE)
    create_date = models.DateTimeField(verbose_name='评论时间', auto_now_add=True)

    reply = models.ForeignKey(verbose_name='回复', to='self', null=True, blank=True, on_delete=models.CASCADE)
    depth = models.PositiveIntegerField(verbose_name='评论层级', default=1)

    favor_count = models.PositiveIntegerField(verbose_name='赞数', default=0)

    # 以后方便通过跟评论找到其所有的子孙评论
    root = models.ForeignKey(verbose_name='根评论', to='self', null=True, blank=True, related_name='descendant',
                             on_delete=models.CASCADE)


class CommentFavorRecord(models.Model):
    """
    评论赞记录
    """
    comment = models.ForeignKey(verbose_name='赞点', to='CommentRecord', on_delete=models.CASCADE)
    user = models.ForeignKey(verbose_name='点赞用户', to='UserInfo', on_delete=models.CASCADE)


class AgreePointDetail(models.Model):
    """
    赞点详细
    """
    key = models.CharField(verbose_name='腾讯对象存储中的文件名', max_length=128, help_text="用于以后在腾讯对象存储中删除")
    cos_path = models.CharField(verbose_name='腾讯对象存储中图片路径', max_length=128)
    agreePoint = models.ForeignKey(verbose_name='赞点', to='AgreePoint', on_delete=models.CASCADE)


class AgreeMessage(models.Model):
    """
    赞同通知Message
    """
    STATUS_NOT_START = 1
    STATUS_START = 2
    STATUS_END = 3

    status_choices = (
        (STATUS_NOT_START, '未开始'),
        (STATUS_START, '进行中'),
        (STATUS_END, '已结束')
    )

    title = models.CharField(verbose_name='标题', max_length=32)
    status = models.PositiveSmallIntegerField(verbose_name='状态', choices=status_choices, default=STATUS_NOT_START)
    content = models.CharField(verbose_name='内容', max_length=10240)
    cover = models.FileField(verbose_name='封面', max_length=128)
    # video = models.CharField(verbose_name='预览视频', max_length=128, null=True, blank=True)
    start_time = models.DateTimeField(verbose_name='通知开始时间')
    end_time = models.DateTimeField(verbose_name='通知结束时间')
    look_count = models.PositiveIntegerField(verbose_name='围观次数', default=0)
    create_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

    class Meta:
        verbose_name_plural = '活动系列'

    def __str__(self):
        return self.title


class AgreeMessageTask(models.Model):
    """ 定时任务 """
    agreeMessage = models.OneToOneField(verbose_name='通知', to='AgreeMessage', on_delete=models.CASCADE)
    task = models.CharField(verbose_name='Celery通知任务ID', max_length=64)
    end_task = models.CharField(verbose_name='Celery通知结束任务ID', max_length=64)


class AgreeBook(models.Model):
    title = models.CharField(verbose_name='书名', max_length=32)
    desc = models.CharField(verbose_name='概要', max_length=256)
    cover = models.FileField(verbose_name='封面', max_length=128)
    read_count = models.PositiveIntegerField(verbose_name='浏览数', default=0)
    author = models.CharField(verbose_name='作者名', max_length=32)
    content = models.CharField(verbose_name='详细内容', max_length=1024)
    url = models.FileField(verbose_name='书', max_length=128)
    order = models.PositiveIntegerField(verbose_name='排序')

    STATUS_VALID = 1
    STATUS_DELETE = 9
    status_choices = (
        (STATUS_VALID, '正常'),
        (STATUS_DELETE, '删除')
    )
    status = models.PositiveSmallIntegerField(verbose_name='状态', choices=status_choices, default=STATUS_VALID)

pyAgreeZone/apps/web/templates/web/agreeBook_add.html
{% extends 'web/layout.html' %}
{% load staticfiles %}
{% block css %}
    <style>
        input[type='file'] {
            min-height: 34px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <form method="post" novalidate enctype="multipart/form-data" autocomplete="off">
            {% csrf_token %}
            <div class="panel panel-default">
                <div class="panel-heading clearfix">{{ formTitle }}
                    <input type="submit" class="btn btn-success btn-xs" value="保 存" style="float: right;">
                </div>
                <div class="panel-body">
                    <div class="form-horizontal clearfix">
                        {% for field in form %}
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="{{ field.id_for_label }}"
                                           class="col-sm-3 control-label">{{ field.label }}</label>
                                    <div class="col-sm-9">
                                        {{ field }}
                                        <span style="color: red;">{{ field.errors.0 }}</span>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>

            </div>

        </form>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'web/kindeditor/kindeditor-all.js' %}"></script>
    <script src="{% static 'web/jquery-3.4.1.min.js' %}"></script>
    <script>
        KindEditor.ready(function (k) {
            window.editor = k.create("#id_content", {
                height: "600",
                uploadJson: "uploadImg/",
                extraFileUploadParams: {
                    csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
                }

            })
        })
    </script>

{% endblock %}

pyAgreeZone/apps/web/templates/web/agreeBook_list.html
{% extends 'web/layout.html' %}

{% block content %}
    <div class="container-fluid">
        <h2>赞书列表</h2>
        <div style="margin: 5px 0;">
            <a href="{% url 'agreeBook_add' %}" class="btn btn-primary">添加</a>
        </div>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>封面</th>
                <th>标题</th>
                <th>作者</th>
                <th>概要</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for item in queryset %}
                <tr>
                    <td>
                        <img style="height: 60px;width: 160px;" src="{{ item.cover }}">
                    </td>
                    <td>{{ item.title }}</td>
                    <td>{{ item.author }}</td>
                    <td>{{ item.desc }}</td>
                    <td>
                        <div class="btn-group btn-group-xs" role="group" aria-label="Small button group">
                            <a class="btn btn-default" href="{% url 'agreeBook_edit' pk=item.id %}">编辑</a>
                            <a class="btn btn-danger"
                               onclick="removeRow(this,'{% url 'agreeBook_delete' pk=item.id %}')">删除</a>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block js %}
    <script>
        function removeRow(ths, url) {
            var result = confirm("确认删除？");
            if (result) {
                $.ajax({
                    url: url,
                    type: 'GET',
                    dataType: "JSON",
                    success: function (arg) {
                        if (arg.status) {
                            $(ths).parent().parent().parent().remove();
                        } else {
                            alert('删除失败');
                        }
                    }
                })
            }
        }
    </script>
{% endblock %}

pyAgreeZone/apps/web/templates/web/agreeDepart_list.html
{% extends 'web/layout.html' %}

{% block content %}
    <div class="container-fluid">
        <h2>部门列表</h2>
        <div style="margin: 5px 0;">
            <a href="{% url 'agreeDepart_add' %}" class="btn btn-primary">添加</a>
        </div>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>部门名</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for item in queryset %}
                <tr>
                    <td>
                        {{ item.name }}
                    </td>
                    <td>
                        <div class="btn-group btn-group-xs" role="group" aria-label="Small button group">
                            <a class="btn btn-default" href="{% url 'agreeDepart_edit' pk=item.id %}">编辑</a>
                            <a class="btn btn-danger"
                               onclick="removeRow(this,'{% url 'agreeDepart_delete' pk=item.id %}')">删除</a>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block js %}
    <script>
        function removeRow(ths, url) {
            var result = confirm("确认删除？");
            if (result) {
                $.ajax({
                    url: url,
                    type: 'GET',
                    dataType: "JSON",
                    success: function (arg) {
                        if (arg.status) {
                            $(ths).parent().parent().parent().remove();
                        } else {
                            alert('删除失败');
                        }
                    }
                })
            }
        }
    </script>
{% endblock %}

pyAgreeZone/apps/web/templates/web/agreeMessage_add.html
{% extends 'web/layout.html' %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" href="{% static 'web/datetimepicker/bootstrap-datetimepicker.min.css' %}">
    <style>
        input[type='file'] {
            min-height: 34px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <form method="post" novalidate enctype="multipart/form-data" autocomplete="off">
            {% csrf_token %}
            <div class="panel panel-default">
                <div class="panel-heading clearfix">{{ formTitle }}
                    <input type="submit" class="btn btn-success btn-xs" value="保 存" style="float: right;">
                </div>
                <div class="panel-body">
                    <div class="form-horizontal clearfix">
                        {% for field in form %}
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label for="{{ field.id_for_label }}"
                                           class="col-sm-3 control-label">{{ field.label }}</label>
                                    <div class="col-sm-9">
                                        {{ field }}
                                        {% if errors and field.name == 'start_time' %}
                                            <span style="color: red">
                                            {{ errors }}
                                            </span>
                                        {% endif %}

                                        <span style="color: red;">{{ field.errors.0 }}</span>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>

            </div>

        </form>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'web/datetimepicker/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'web/datetimepicker/bootstrap-datetimepicker.zh-CN.js' %}"></script>
    <script src="{% static 'web/kindeditor/kindeditor-all.js' %}"></script>
    <script>
        Date.prototype.Format = function (fmt) { //author: meizz
            var o = {
                "M+": this.getMonth() + 1, //月份
                "d+": this.getDate(), //日
                "h+": this.getHours(), //小时
                "m+": this.getMinutes(), //分
                "s+": this.getSeconds(), //秒
                "q+": Math.floor((this.getMonth() + 3) / 3), //季度
                "S": this.getMilliseconds() //毫秒
            };
            if (/(y+)/.test(fmt)) fmt = fmt.replace(RegExp.$1, (this.getFullYear() + "").substr(4 - RegExp.$1.length));
            for (var k in o)
                if (new RegExp("(" + k + ")").test(fmt)) fmt = fmt.replace(RegExp.$1, (RegExp.$1.length == 1) ? (o[k]) : (("00" + o[k]).substr(("" + o[k]).length)));
            return fmt;
        };

        $(function () {
            initDatepicker();
        });

        function initDatepicker() {
            $('#id_start_time,#id_end_time').datetimepicker({
                language: "zh-CN",
                minView: "hour", // month
                sideBySide: true,
                format: 'yyyy-mm-dd hh:ii',
                bootcssVer: 3,
                startDate: new Date(),
                autoclose: true
            })
        }

    </script>
    <script>
        KindEditor.ready(function (k) {
            window.editor = k.create("#id_content", {
                height: "600",
                uploadJson: "uploadImg/",
                extraFileUploadParams: {
                    csrfmiddlewaretoken: $("[name='csrfmiddlewaretoken']").val()
                }

            })
        })
    </script>

{% endblock %}

pyAgreeZone/apps/web/templates/web/agreeMessage_list.html
{% extends 'web/layout.html' %}

{% block content %}
    <div class="container-fluid">
        <h2>通知列表</h2>
        <div style="margin: 5px 0;">
            <a href="{% url 'agreeMessage_add' %}" class="btn btn-primary">添加</a>
        </div>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>封面</th>
                <th>标题</th>
{#                <th>内容</th>#}
                <th>开始时间</th>
                <th>结束时间</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for item in queryset %}
                <tr>
                    <td>
                        <img style="height: 60px;width: 160px;" src="{{ item.cover }}">
                    </td>
                   <td>{{ item.title }}</td>
{#                   <td>{{ item.content }}</td>#}
                    <td>{{ item.start_time|date:"Y-m-d H:i" }}</td>
                    <td>{{ item.end_time|date:"Y-m-d H:i" }}</td>
                    <td>{{ item.get_status_display }}</td>
                    <td>
                        <div class="btn-group btn-group-xs" role="group" aria-label="Small button group">
                            <a class="btn btn-default" href="{% url 'agreeMessage_edit' pk=item.id %}">编辑</a>
                            <a class="btn btn-danger"
                               onclick="removeRow(this,'{% url 'agreeMessage_delete' pk=item.id %}')">删除</a>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block js %}
    <script>
        function removeRow(ths, url) {
            var result = confirm("确认删除？");
            if (result) {
                $.ajax({
                    url: url,
                    type: 'GET',
                    dataType: "JSON",
                    success: function (arg) {
                        if (arg.status) {
                            $(ths).parent().parent().parent().remove();
                        } else {
                            alert('删除失败');
                        }
                    }
                })
            }
        }
    </script>
{% endblock %}

pyAgreeZone/apps/web/templates/web/agreeTopic_list.html
{% extends 'web/layout.html' %}

{% block content %}
    <div class="container-fluid">
        <h2>话题列表</h2>
        <div style="margin: 5px 0;">
            <a href="{% url 'agreeTopic_add' %}" class="btn btn-primary">添加</a>
        </div>
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>话题</th>
                <th>关注度</th>
                <th>状态</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for item in queryset %}
                <tr>
                    <td>
                        {{ item.title }}
                    </td>
                   <td>{{ item.count }}</td>
                    <td>{{ item.get_status_display }}</td>
                    <td>
                        <div class="btn-group btn-group-xs" role="group" aria-label="Small button group">
                            <a class="btn btn-default" href="{% url 'agreeTopic_edit' pk=item.id %}">编辑</a>
                            <a class="btn btn-danger"
                               onclick="removeRow(this,'{% url 'agreeTopic_delete' pk=item.id %}')">删除</a>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block js %}
    <script>
        function removeRow(ths, url) {
            var result = confirm("确认删除？");
            if (result) {
                $.ajax({
                    url: url,
                    type: 'GET',
                    dataType: "JSON",
                    success: function (arg) {
                        if (arg.status) {
                            $(ths).parent().parent().parent().remove();
                        } else {
                            alert('删除失败');
                        }
                    }
                })
            }
        }
    </script>
{% endblock %}

pyAgreeZone/apps/web/templates/web/agreeUser_list.html
{% extends 'web/layout.html' %}

{% block content %}
    <div class="container-fluid">
        <h2>用户列表</h2>

        <table class="table table-bordered">
            <thead>
            <tr>
                <th>头像</th>
                <th>昵称</th>
                <th>手机号</th>
                <th>部门</th>
                <th>部门认证状态</th>
                <th>部门认证</th>
            </tr>
            </thead>
            <tbody>
            {% for item in queryset %}
                <tr>
                    <td>
                        <img style="height: 60px;" src="{{ item.avatar }}">
                    </td>
                    <td>{{ item.nickname }}</td>
                    <td>{{ item.telephone }}</td>
                    <td>{{ item.depart }}</td>
                    <td>{{ item.get_depart_status_display }}</td>
                    <td>
                        <div class="btn-group btn-group-xs" role="group" aria-label="Small button group">
                            {% if item.depart_status == 1 %}
                                <a class="btn btn-danger" href="{% url 'agreeUser_depart_deny' pk=item.id %}">拒绝认证</a>

                            {% elif item.depart_status == 3 %}
                                <a class="btn btn-default" href="{% url 'agreeUser_depart_pass' pk=item.id %}">通过认证</a>
                            {% else %}
                                <a class="btn btn-default" href="{% url 'agreeUser_depart_pass' pk=item.id %}">通过认证</a>
                                <a class="btn btn-danger" href="{% url 'agreeUser_depart_deny' pk=item.id %}">拒绝认证</a>
                            {% endif %}
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

pyAgreeZone/apps/web/templates/web/common_form.html
{% extends 'web/layout.html' %}
{% load staticfiles %}
{% block css %}
    <link rel="stylesheet" href="{% static 'web/datetimepicker/bootstrap-datetimepicker.min.css' %}">
    <style>
        input[type='file'] {
            min-height: 34px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <form method="post" novalidate enctype="multipart/form-data" autocomplete="off">
            {% csrf_token %}
            <div class="panel panel-default">
                <div class="panel-heading clearfix">{{ formTitle }}
                    <input type="submit" class="btn btn-success btn-xs" value="保 存" style="float: right;">
                </div>
                <div class="panel-body">
                    <div class="form-horizontal clearfix">
                        {% for field in form %}
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label for="{{ field.id_for_label }}"
                                           class="col-sm-3 control-label">{{ field.label }}</label>
                                    <div class="col-sm-9">
                                        {{ field }}
                                        <span style="color: red;">{{ field.errors.0 }}</span>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script src="{% static 'web/datetimepicker/bootstrap-datetimepicker.min.js' %}"></script>
    <script src="{% static 'web/datetimepicker/bootstrap-datetimepicker.zh-CN.js' %}"></script>
    <script>
        Date.prototype.Format = function (fmt) { //author: meizz
            var o = {
                "M+": this.getMonth() + 1, //月份
                "d+": this.getDate(), //日
                "h+": this.getHours(), //小时
                "m+": this.getMinutes(), //分
                "s+": this.getSeconds(), //秒
                "q+": Math.floor((this.getMonth() + 3) / 3), //季度
                "S": this.getMilliseconds() //毫秒
            };
            if (/(y+)/.test(fmt)) fmt = fmt.replace(RegExp.$1, (this.getFullYear() + "").substr(4 - RegExp.$1.length));
            for (var k in o)
                if (new RegExp("(" + k + ")").test(fmt)) fmt = fmt.replace(RegExp.$1, (RegExp.$1.length == 1) ? (o[k]) : (("00" + o[k]).substr(("" + o[k]).length)));
            return fmt;
        };

        $(function () {
            initDatepicker();
        });

        function initDatepicker() {
            $('#id_start_time,#id_end_time').datetimepicker({
                language: "zh-CN",
                minView: "hour", // month
                sideBySide: true,
                format: 'yyyy-mm-dd hh:ii',
                bootcssVer: 3,
                startDate: new Date(),
                autoclose: true
            })
        }

    </script>

{% endblock %}

pyAgreeZone/apps/web/templates/web/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'web/images/logo.ico' %}" >
    <title>赞圈er管理平台</title>
    <link rel="stylesheet" href="{% static 'web/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/common.css' %}">
    <style>

    </style>
    {% block css %}


    {% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">赞圈er管理平台</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">赞圈er管理平台</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'agreeMessage_list' %}">通知管理</a></li>
                <li><a href="{% url 'agreeTopic_list' %}">话题管理</a></li>
                <li><a href="{% url 'agreeDepart_list' %}">部门管理</a></li>
                <li><a href="{% url 'agreeBook_list' %}">赞书管理</a></li>
                <li><a href="{% url 'agreeUser_list' %}">用户管理</a></li>
            </ul>
            <div class="right-menu right clearfix">

                <div style="float: right;margin-top: 8px;">
                    <a href="/logout/" class="avatar" >
                        <img class="img-circle"  title="点击注销" style="width: 35px;height: 35px;" src="{% static 'web/images/user.png' %}">
                    </a>
                </div>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
</nav>

<div class="pg-body">
    {% block content %} {% endblock %}
</div>

<script src="{% static 'web/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'web/bootstrap/js/bootstrap.min.js' %}"></script>
{% block js %} {% endblock %}

</body>
</html>